# Use the official Python Alpine image from Docker Hub
FROM python:3.9-alpine

# Set the working directory inside the container
WORKDIR /app

# Copy the Python script into the container
COPY add.py .

# Install any additional dependencies if needed
# Example: RUN pip install some-package

# Set the command to run the Python script when the container starts
CMD ["python", "add.py"]
    